# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - 'master'       # Run the workflow when pushing to the main branch
  pull_request:
    branches:
      - '*'          # Run the workflow for all pull requests
  release:
    types:
      - published    # Run the workflow when a new GitHub release is published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup NuGet.exe for use with Actions
      uses: NuGet/setup-nuget@v1.1.1
      with:
        nuget-version: latest
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Package nuget
      run: dotnet pack --configuration release
    - name: Nuget Configure
      run: dotnet nuget add source --username patrickschaller --password ${{ github.token }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/2DeadPixels/index.json
    - name: Nuget Publish - GitHub
      run: dotnet nuget push "**/*.nupkg"  --api-key ${{ github.token }} --source "github" --skip-duplicate
   # - name: Push generated package to GitHub registry
   #   run: dotnet nuget push ./package/*.nupkg --api-key ${{ github.token }} --source ${{env.REPOSITORY_URL}}
      # --source https://nuget.pkg.github.com/2DeadPixels/index.json   --api-key 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 
